### ISSUE TITLE
Letter F on Domain list

### ISSUE THREAD

**Issue by esin** [densitydesign/teaching-dd15#2]
Hi
Looks like something happened with letter F on page The Physical
Internet in Internet domains - black square disappeared

**Comment by andreabenedetti** [comment]
Hi, could you be a bit more specific and provide me screenshots of this issue? Thanks!

**Comment by esin** [comment]
Sure
![IMG_20191211_150309](https://user-images.githubusercontent.com/69767/70620092-64e12380-1c27-11ea-92f3-05ee57504144.jpg)

**Comment by andreabenedetti** [comment]
Thanks! The error has been fixed :)
